### PR TITLE
Add detached content converter

### PR DESCRIPTION
**Pull request by kentakayama**
This PR adds two classmethods converting between common form of COSE message (I call it "attached") and detached content COSE message.
[Section 2 of RFC 9052](https://datatracker.ietf.org/doc/html/rfc9052#section-2-2.3) describes about it.

For example, [the ECDSA example](https://github.com/cose-wg/Examples/blob/master/ecdsa-examples/ecdsa-sig-01.json) (in cbor-diag),
``` diag
18([
  / protected: / h'A201260300',
  / unprotected: / {4: h'3131'},
  / payload: / h'546869732069732074686520636F6E74656E742E',
  / signature: / h'6520BBAF2081D7E0ED0F95F76EB0733D667005F7467CEC4B87B9381A6BA1EDE8
                   E00DF29F32A37230F39A842A54821FDD223092819D7728EFB9D3A0080B75380B'
])
```
can be separated into two binaries (in cbor-diag)
``` diag
18([
  / protected: / h'A201260300',
  / unprotected: / {4: h'3131'},
  / payload: / null / so called "detached content" /,
  / signature: / h'6520BBAF2081D7E0ED0F95F76EB0733D667005F7467CEC4B87B9381A6BA1EDE8
                   E00DF29F32A37230F39A842A54821FDD223092819D7728EFB9D3A0080B75380B'
])
```
and the detached payload is (in hex)
``` hex
546869732069732074686520636F6E74656E742E
```

## The reason why do I request this feature 
[SUIT Manifest](https://github.com/suit-wg/manifest-spec/blob/c504fde8d7e7a859b6717243e088900bad96f92d/examples/example0.txt#L15) and [its extension](https://github.com/suit-wg/suit-firmware-encryption/blob/6f186a59b28b451587b8b823049364456ad07820/examples/suit-manifest-aes-kw-content.diag.signed#L39) leverage it.

The reasons why I've tried to implment them as classmethod are
- adding an argument `to_detached_content: bool = Fase` to `encode()` method would change the type of return value from `Union[bytes, CBORTag]` to `Tuple[Union[bytes, CBORTag], bytes]`
- adding another public method like `encode_detached()` would complicate the interface of COSE class
- converting operation can be separately executed to both encode and decode

Can you give me some advice?

### CODE REVIEW

**Comment by dajiaji** [comment]
First of all, thank you very much for the PR to add detached payload feature!

> - adding an argument to_detached_content: bool = Fase to encode() method would change the type of return value from Union[bytes, CBORTag] to Tuple[Union[bytes, CBORTag], bytes]

Yes, it's a big breaking change so I cannot pick this up for now. 

> - adding another public method like encode_detached() would complicate the interface of COSE class converting operation can be separately executed to both encode and decode

Agree with you.

> converting operation can be separately executed to both encode and decode

Sounds reasonable.
I like this approach, but I introduced COSEMessage class to modify encoded COSE message before (mainly for countersigning feature).

Could you consider moving your `attached_to_detached` function to under COSEMessage as follows?

```py
msg, payload = COSEMessage.loads(encoded_cose_message).to_detached()
```

Sorry for the lack of documentation about COSEMessage. If you have some problem to try this, feel free to ask me. I'll consider accepting this PR as is.

**Comment by kentakayama** [comment]
> I like this approach, but I introduced COSEMessage class to modify encoded COSE message before (mainly for countersigning feature).
> 
> Could you consider moving your `attached_to_detached` function to under COSEMessage as follows?
> 
> ```python
> msg, payload = COSEMessage.loads(encoded_cose_message).to_detached()
> ```

This information helped me a lot. Let me try it.

**Comment by dajiaji** [comment]
detach() might be better than to_detached()... 
I leave it to you @kentakayama

**Comment by kentakayama** [comment]
@dajiaji 
Named `.detach_payload()` and `.attach_payload(payload)` .

**Comment by kentakayama** [comment]
Oops, do you know how can I fix this error?
https://results.pre-commit.ci/run/github/358796154/1697187288.YLv6NSW9TX-wOs8VB7CEmw

**Comment by dajiaji** [comment]
> Oops, do you know how can I fix this error? https://results.pre-commit.ci/run/github/358796154/1697187288.YLv6NSW9TX-wOs8VB7CEmw

Could you try the following？

- Add `from __future__ import annotations`  to the top of the cose_message.py
- Replace `Self` to `COSEMessage`.

**Review by dajiaji — APPROVED** [review]

**Comment by kentakayama** [comment]
@dajiaji 
Thanks! It worked fine.

There might be an arguable point that which field should hold the original payload, `self._msg[2]` or `self._payload`.
At this moment, combining detached-content and countersign may cause unexpected behavior.
For example,
1. encoded = COSE.loads()
2. detached, payload = COSEMessage.loads(encoded.dumps()).detach_payload()
3. detached.countersign()

**Comment by kentakayama** [comment]
And the CI says that test on `__eq__` and `__ne__` are not enough. My apologies.

**Comment by dajiaji** [comment]
@kentakayama 

> At this moment, combining detached-content and countersign may cause unexpected behavior.

I'd like to clarify your concern. Does the unexpected behavior mean the `3.   countersign` cannot countersign the ToBeSigned structure including the payload (because `self._msg[2]` (and `self._payload`) are nil after calling `detach_payload`)?

If my interpretation is correct, to resolve the problem, I think it would be better to regard `detach_payload` as an irreversible operation, remove the attach_payload function, and allow the `countersign` and `counterverify` functions to take an optional `detached_payload` parameter.

What do you think?

**Comment by dajiaji** [comment]
> And the CI says that test on __eq__ and __ne__ are not enough. My apologies.

No problem. I can add the tests.
My review was not sufficient but it might be better to fix the comparison of other_fields on __eq___ and __ne___.

**Comment by kentakayama** [comment]
> Does the unexpected behavior mean the 3.   countersign cannot countersign the ToBeSigned structure including the payload (because self._msg[2] (and self._payload) are nil after calling detach_payload)?

Right. We have several solutions,
## 1. Allow both _msg[2] and _payload to have nil (Yours)
Both counersign and counterverify on detached message require argument detached_payload.

## 2. Make _msg[2] to always have the actual payload, but allow _payload to have nil
Let COSEMessage constructor like
```python
def __init__(self, type, msg, detached_payload = None):
    if msg[2] is None:
        if not isinstance(detached_payload, bytes):
            raise ValueError()
        self._msg = [*msg[0:2], detached_payload, *msg[3:]]
        self._payload = None
    else:
        self._msg = msg # or list(msg) not to care the msg will be alternated outside
        self._payload = msg[2]
```

We can change detach_payload and attach_payload not to create new instance but just set the _payload None and augument detached_payload respectively.
They don't change the _msg, so that both countersign and counterverify _msg[2] never fail.

**Pull request merged**
